# Generated by Django 5.1.7 on 2025-04-10 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuicola',
            fields=[
                ('id_acuicola', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('RFC', models.CharField(max_length=13, unique=True)),
                ('ubicacion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alimentar',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_alimento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('lote', models.CharField(max_length=30)),
                ('kg', models.FloatField()),
                ('mortalidad', models.FloatField()),
                ('clima', models.CharField(max_length=255)),
                ('observacion', models.CharField(max_length=255)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_entrada_producto', models.AutoField(primary_key=True, serialize=False)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estanque',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_estanque', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('forma', models.CharField(max_length=255)),
                ('superficie', models.FloatField()),
                ('profundidad', models.FloatField()),
                ('infraestructura', models.CharField(max_length=255)),
                ('ubicacion', models.TextField()),
                ('estatus', models.BooleanField(default=0)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField()),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rubro', models.CharField(max_length=255)),
                ('porcentaje_proteina', models.FloatField()),
                ('presentacion', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntradaUnitaria',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_entrada_unitaria', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_kg', models.FloatField()),
                ('unidades', models.IntegerField()),
                ('costo', models.FloatField()),
                ('lote', models.CharField(max_length=255)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entrada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='provedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedor'),
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=255)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_salida_producto', models.AutoField(primary_key=True, serialize=False)),
                ('solicitante', models.IntegerField()),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalidaUnitaria',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_salida_unitaria', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=255)),
                ('cantidad', models.FloatField()),
                ('cantidad_kg', models.FloatField()),
                ('destino', models.TextField()),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_siembra', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=255)),
                ('cantidad_organismos', models.IntegerField()),
                ('peso_promedio', models.FloatField()),
                ('tamano_promedio', models.FloatField()),
                ('etapa', models.CharField(max_length=255)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('estanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estanque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalidaEstanque',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_salida_estanque', models.AutoField(primary_key=True, serialize=False)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salidaunitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salidaunitaria')),
                ('siembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siembra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_dieta', models.AutoField(primary_key=True, serialize=False)),
                ('kg_diarios', models.FloatField()),
                ('peso_meta', models.FloatField()),
                ('tiempo_dias', models.IntegerField()),
                ('frecuencia', models.IntegerField()),
                ('notas', models.CharField(max_length=255)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alimentar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('siembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siembra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crecimiento',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_crecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('medicion', models.FloatField()),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rubro')),
                ('siembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siembra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_cosecha', models.AutoField(primary_key=True, serialize=False)),
                ('biomasa_real', models.FloatField()),
                ('destino', models.CharField(max_length=255)),
                ('documento', models.TextField()),
                ('transporte', models.TextField()),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('siembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siembra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalidadAgua',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_calidad_agua', models.AutoField(primary_key=True, serialize=False)),
                ('temperatura', models.FloatField()),
                ('oxigeno_disuelto', models.FloatField()),
                ('ph', models.FloatField()),
                ('nitritos', models.FloatField()),
                ('nitratos', models.FloatField()),
                ('sulfato', models.FloatField()),
                ('fosfato', models.FloatField()),
                ('cloro', models.FloatField()),
                ('salinidad', models.FloatField()),
                ('amonio', models.FloatField()),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('siembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siembra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alimentar',
            name='siembra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siembra'),
        ),
        migrations.CreateModel(
            name='Adicion',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_adicion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_organismos', models.IntegerField()),
                ('peso_promedio', models.FloatField()),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('siembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siembra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('sueldo', models.FloatField()),
                ('acuicola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=1)),
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('tipo', models.TextField()),
                ('cantidad', models.FloatField()),
                ('frecuencia', models.TextField()),
                ('observacion', models.CharField(max_length=255)),
                ('acuicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.acuicola')),
                ('siembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siembra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
