# Generated by Django 5.1.7 on 2025-07-23 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configuracionnomina_pagonomina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_anterior', models.FloatField()),
                ('sueldo_nuevo', models.FloatField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfil')),
            ],
        ),
    ]
